const BASE='/functions/v1/kssenger-app';
const $=(id)=>document.getElementById(id);
const state={me:null,contacts:[],peer:null,authMode:'login',heartbeat:null,poll:null,pendingSignup:null,lastMessageId:0};
const presenceLabel={online:'🟢 Disponible',busy:'🔴 Occupé',away:'🟠 Absent',invisible:'⚫ Invisible',offline:'⚫ Hors ligne'};

async function api(path,{method='GET',body}={}){
 const r=await fetch(BASE+path,{method,credentials:'same-origin',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined,cache:'no-store'});
 let data={};try{data=await r.json()}catch{}
 if(!r.ok){const e=new Error(data.error||`HTTP ${r.status}`);e.status=r.status;throw e}return data;
}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.remove('hidden');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.add('hidden'),2400)}
function setMsg(id,msg,ok=false){const el=$(id);el.textContent=msg||'';el.style.color=ok?'#268856':'#c23f4b'}
function setView(name){for(const id of ['authView','profileView','appView'])$(id).classList.add('hidden');$(name).classList.remove('hidden')}
function avatarLetter(p){return (p?.nickname||p?.username||'?').trim().charAt(0).toUpperCase()||'?'}
function effectiveStatus(p){if(!p||p.status==='invisible')return'offline';const seen=Date.parse(p.last_seen_at||0);return(!seen||Date.now()-seen>95000)?'offline':(p.status||'offline')}
function stopLoops(){if(state.heartbeat)clearInterval(state.heartbeat);if(state.poll)clearInterval(state.poll);state.heartbeat=state.poll=null}
async function touch(status){try{await api('/api/presence',{method:'POST',body:{status}})}catch{}}
function startLoops(){stopLoops();touch(state.me?.status||'online');state.heartbeat=setInterval(()=>touch(state.me?.status||'online'),30000);state.poll=setInterval(async()=>{await Promise.all([loadContacts(),loadRequests()]);if(state.peer)await loadMessages(true)},2500)}
function friendly(err){const m=(err?.message||'').toLowerCase();if(m.includes('invalid_login'))return'Email ou mot de passe incorrect.';if(m.includes('account_or_username_exists'))return'Email déjà utilisé ou identifiant déjà pris.';if(m.includes('invalid_password'))return'Utilise un mot de passe d’au moins 10 caractères.';if(m.includes('invalid_email'))return'Adresse email invalide.';if(m.includes('invalid_username'))return'Identifiant invalide (3 à 24 caractères).';if(m.includes('already_contacts'))return'Vous êtes déjà contacts.';if(m.includes('user_not_found'))return'Utilisateur introuvable.';if(m.includes('blocked'))return'Action impossible avec cet utilisateur.';if(m.includes('contacts_only'))return'Vous devez être contacts pour discuter.';if(m.includes('wizz_cooldown'))return'Wizz en recharge… attends quelques secondes ⚡';if(m.includes('rate_limited'))return'Trop de tentatives. Réessaie plus tard.';if(m.includes('username_taken'))return'Cet identifiant est déjà pris.';return err?.message||'Une erreur est survenue.'}

async function init(){
 try{const d=await api('/api/me');state.me=d.user;enterApp()}catch(e){if(e.status===401)showAuth();else{$('boot').innerHTML='K-SSENGER <small>service indisponible</small>'}}
}
function showAuth(){stopLoops();state.me=null;state.peer=null;$('boot').classList.add('hidden');setView('authView')}
async function enterApp(){renderMe();$('boot').classList.add('hidden');setView('appView');await Promise.all([loadContacts(),loadRequests()]);startLoops()}
function renderMe(){$('meNickname').textContent=state.me.nickname;$('meHandle').textContent='@'+state.me.username;$('meMood').textContent=state.me.mood||'';$('meMusic').textContent=state.me.music?'🎵 '+state.me.music:'';$('meDot').className='presence-dot '+effectiveStatus(state.me)}
function authMode(mode){state.authMode=mode;$('loginTab').classList.toggle('active',mode==='login');$('signupTab').classList.toggle('active',mode==='signup');$('authSubmit').textContent=mode==='login'?'Se connecter':'Continuer';$('password').autocomplete=mode==='login'?'current-password':'new-password';setMsg('authMessage','')}
$('loginTab').onclick=()=>authMode('login');$('signupTab').onclick=()=>authMode('signup');
$('authForm').addEventListener('submit',async e=>{e.preventDefault();setMsg('authMessage','');const email=$('email').value.trim(),password=$('password').value,btn=$('authSubmit');btn.disabled=true;try{if(state.authMode==='signup'){if(password.length<10)throw new Error('invalid_password');state.pendingSignup={email,password};$('username').value='';$('nickname').value='';$('mood').value='';$('music').value='';$('status').value='online';setView('profileView')}else{await api('/api/login',{method:'POST',body:{email,password}});const d=await api('/api/me');state.me=d.user;enterApp()}}catch(err){setMsg('authMessage',friendly(err))}finally{btn.disabled=false}});

$('profileForm').addEventListener('submit',async e=>{e.preventDefault();const profile={username:$('username').value.trim(),nickname:$('nickname').value.trim(),mood:$('mood').value.trim(),music:$('music').value.trim(),status:$('status').value};try{if(state.pendingSignup){await api('/api/signup',{method:'POST',body:{...state.pendingSignup,username:profile.username,nickname:profile.nickname}});state.pendingSignup=null;await api('/api/profile',{method:'POST',body:profile})}else await api('/api/profile',{method:'POST',body:profile});const d=await api('/api/me');state.me=d.user;setMsg('profileMessage','',true);enterApp()}catch(err){setMsg('profileMessage',friendly(err))}});
$('editProfile').onclick=()=>{if(!state.me)return;$('username').value=state.me.username;$('nickname').value=state.me.nickname;$('mood').value=state.me.mood||'';$('music').value=state.me.music||'';$('status').value=state.me.status==='offline'?'online':state.me.status;state.pendingSignup=null;setView('profileView')};

for(const b of document.querySelectorAll('.top-tabs button'))b.onclick=()=>{document.querySelectorAll('.top-tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.panel+'Panel').classList.add('active')};
async function loadContacts(){try{const d=await api('/api/contacts');state.contacts=d.contacts||[];renderContacts();if(state.peer){const fresh=state.contacts.find(x=>x.id===state.peer.id);if(fresh){state.peer=fresh;renderPeerHeader()}}}catch{}}
function renderContacts(){const root=$('contactsList');root.replaceChildren();$('contactsEmpty').classList.toggle('hidden',state.contacts.length>0);for(const p of state.contacts){const card=document.createElement('button');card.type='button';card.className='contact-card';const av=document.createElement('span');av.className='contact-avatar';av.textContent=avatarLetter(p);const d=document.createElement('span');d.className='presence-dot '+effectiveStatus(p);av.appendChild(d);const copy=document.createElement('span');copy.className='contact-copy';const strong=document.createElement('strong');strong.textContent=p.nickname;const line=document.createElement('span');line.textContent=`${presenceLabel[effectiveStatus(p)]||'⚫ Hors ligne'} · @${p.username}`;const sub=document.createElement('span');sub.textContent=p.music?'🎵 '+p.music:(p.mood||'');copy.append(strong,line,sub);card.append(av,copy);card.onclick=()=>openChat(p);root.append(card)}}
$('refreshContacts').onclick=()=>Promise.all([loadContacts(),loadRequests()]);

async function loadRequests(){try{const d=await api('/api/requests'),rows=d.requests||[];$('requestBadge').textContent=rows.length;$('requestBadge').classList.toggle('hidden',!rows.length);$('requestsEmpty').classList.toggle('hidden',!!rows.length);const root=$('requestsList');root.replaceChildren();for(const r of rows){const card=document.createElement('div');card.className='contact-card';const av=document.createElement('span');av.className='contact-avatar';av.textContent=avatarLetter(r);const copy=document.createElement('span');copy.className='contact-copy';const s=document.createElement('strong');s.textContent=r.nickname;const u=document.createElement('span');u.textContent='@'+r.username;copy.append(s,u);const actions=document.createElement('span');actions.className='row-actions';const yes=document.createElement('button');yes.textContent='✓';yes.onclick=async()=>{try{await api(`/api/request/${r.id}/accept`,{method:'POST'});toast(`${r.nickname} ajouté`);await Promise.all([loadRequests(),loadContacts()])}catch(e){toast(friendly(e))}};const no=document.createElement('button');no.textContent='×';no.onclick=async()=>{try{await api(`/api/request/${r.id}/decline`,{method:'POST'});loadRequests()}catch{}};actions.append(yes,no);card.append(av,copy,actions);root.append(card)}}catch{}}

$('searchForm').addEventListener('submit',async e=>{e.preventDefault();try{const d=await api('/api/search?q='+encodeURIComponent($('searchInput').value.trim()));renderSearch(d.users||[]);setMsg('searchMessage',d.users?.length?'':'Aucun utilisateur trouvé.')}catch(err){setMsg('searchMessage',friendly(err))}});
function renderSearch(rows){const root=$('searchList');root.replaceChildren();for(const p of rows){const card=document.createElement('div');card.className='contact-card';const av=document.createElement('span');av.className='contact-avatar';av.textContent=avatarLetter(p);const copy=document.createElement('span');copy.className='contact-copy';const s=document.createElement('strong');s.textContent=p.nickname;const u=document.createElement('span');u.textContent='@'+p.username;copy.append(s,u);const actions=document.createElement('span');actions.className='row-actions';const add=document.createElement('button');add.textContent='Ajouter';add.onclick=async()=>{try{await api('/api/request',{method:'POST',body:{username:p.username}});toast('Invitation envoyée');add.disabled=true}catch(e){toast(friendly(e))}};actions.append(add);card.append(av,copy,actions);root.append(card)}}

async function openChat(p){state.peer=p;state.lastMessageId=0;$('welcomeChat').classList.add('hidden');$('chatView').classList.remove('hidden');$('appView').classList.add('chat-open');renderPeerHeader();await loadMessages(false)}
function renderPeerHeader(){if(!state.peer)return;$('peerAvatar').textContent=avatarLetter(state.peer);$('peerNickname').textContent=state.peer.nickname;$('peerStatus').textContent=presenceLabel[effectiveStatus(state.peer)]||'⚫ Hors ligne';$('peerMusic').textContent=state.peer.music?'🎵 '+state.peer.music:(state.peer.mood||'');$('peerDot').className='presence-dot '+effectiveStatus(state.peer)}
$('mobileBack').onclick=()=>$('appView').classList.remove('chat-open');
async function loadMessages(fromPoll=false){if(!state.peer)return;try{const d=await api('/api/messages?peer='+encodeURIComponent(state.peer.id)),rows=d.messages||[];const latest=rows.at(-1);if(fromPoll&&latest&&latest.id>state.lastMessageId&&latest.sender_id===state.peer.id){if(latest.kind==='wizz')doWizz(`${state.peer.nickname} t'envoie un Wizz ⚡`);else toast('💬 Nouveau message')}state.lastMessageId=latest?.id||state.lastMessageId;renderMessages(rows)}catch{}}
function renderMessages(rows){const root=$('messages'),atBottom=root.scrollHeight-root.scrollTop-root.clientHeight<90;root.replaceChildren();for(const m of rows){if(m.kind==='wizz'){const w=document.createElement('div');w.className='wizz-message';w.textContent=(m.sender_id===state.me.id?'Tu as envoyé':'Tu as reçu')+' un ⚡ Wizz';root.append(w);continue}const row=document.createElement('div');row.className='message-row '+(m.sender_id===state.me.id?'mine':'theirs');const b=document.createElement('div');b.className='bubble';const text=document.createElement('div');text.textContent=m.body;const t=document.createElement('time');t.textContent=new Date(m.created_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});b.append(text,t);row.append(b);root.append(row)}if(atBottom||rows.length<20)root.scrollTop=root.scrollHeight}
$('messageForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.peer)return;const input=$('messageInput'),body=input.value.trim();if(!body)return;input.value='';try{await api('/api/send',{method:'POST',body:{peer:state.peer.id,body,kind:'text'}});await loadMessages(false)}catch(err){toast(friendly(err));input.value=body}});
$('wizz').onclick=async()=>{if(!state.peer)return;try{await api('/api/send',{method:'POST',body:{peer:state.peer.id,body:'WIZZ',kind:'wizz'}});doWizz('Wizz envoyé ⚡');await loadMessages(false)}catch(err){toast(friendly(err))}};
function doWizz(text){const shell=$('chatView');shell.classList.remove('wizzing');void shell.offsetWidth;shell.classList.add('wizzing');setTimeout(()=>shell.classList.remove('wizzing'),900);$('wizzBanner').textContent=text;$('wizzBanner').classList.remove('hidden');setTimeout(()=>$('wizzBanner').classList.add('hidden'),1300);if(navigator.vibrate)navigator.vibrate([80,40,80])}
$('blockPeer').onclick=async()=>{if(!state.peer||!confirm(`Bloquer ${state.peer.nickname} ? Vous ne pourrez plus vous écrire.`))return;try{await api('/api/block',{method:'POST',body:{peer:state.peer.id}});toast('Utilisateur bloqué');state.peer=null;$('chatView').classList.add('hidden');$('welcomeChat').classList.remove('hidden');$('appView').classList.remove('chat-open');loadContacts()}catch(err){toast(friendly(err))}};
$('logout').onclick=async()=>{try{await api('/api/logout',{method:'POST'})}catch{}showAuth()};
document.addEventListener('visibilitychange',()=>{if(!state.me)return;if(document.visibilityState==='visible'){touch(state.me.status||'online');loadContacts()}else touch('away')});
window.addEventListener('beforeunload',stopLoops);
init();
