import { chromium } from 'playwright';
const browser = await chromium.launch();
const context = await browser.newContext({ storageState: '.auth/kenams.json', baseURL: 'https://k-ssenger.expo.app' });
const page = await context.newPage();
await page.goto('https://k-ssenger.expo.app');
await page.waitForTimeout(3000);
await page.getByPlaceholder(/Rechercher un contact/i).fill('kenams');
await page.waitForTimeout(1500);
await page.screenshot({ path: 'lookup-kenams.png' });
console.log(await page.locator('body').innerText());
await browser.close();
